# --- Project Metadata ---
sonar.projectKey=Tugamer89_AC-Virtual-Engineer
sonar.organization=tugamer89

sonar.projectName=AC Virtual Engineer
# x-release-please-start-version
sonar.projectVersion=0.1.9
# x-release-please-end

# --- Sources ---
sonar.sources=backend, frontend/src, .github/workflows, .githooks

# --- Global Exclusions ---
sonar.exclusions=**/node_modules/**, **/venv/**, **/env/**, frontend/dist/**, **/package-lock.json, **/*.css, **/*.svg, frontend/public/**, backend/requirements*.txt
sonar.coverage.exclusions=**/*

# --- Python (Backend) ---
sonar.python.version=3.13

# --- TypeScript/JavaScript (Frontend) ---
sonar.typescript.tsconfigPath=frontend/tsconfig.json

# --- Settings ---
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
