import { useEffect, useState, useRef } from "react";
import {
  Activity,
  Gauge,
  Car,
  AlertTriangle,
  Clock,
  ArrowDownToLine,
} from "lucide-react";
import mqtt from "mqtt";

interface TelemetryData {
  speed_kmh: number;
  gas: number;
  brake: number;
  engine_rpm: number;
  max_rpm: number;
  steer_angle: number;
  gear: number;
  slip_angle: number[];
  car_name: string;
  track_name: string;
  lap_time: number;
  last_lap: number;
  best_lap: number;
  suspension_height: number[];
}

export default function App() {
  const [telemetry, setTelemetry] = useState<TelemetryData | null>(null);
  const [isConnected, setIsConnected] = useState(false);
  const [status, setStatus] = useState<
    "disconnected" | "connecting" | "connected"
  >("disconnected");
  const [pin, setPin] = useState("");

  const pcRef = useRef<RTCPeerConnection | null>(null);

  const startConnection = async () => {
    if (pin.length !== 6) return;
    setStatus("connecting");

    const brokerUrl = import.meta.env.VITE_MQTT_WS_URL;
    const topicHost = `acve/signaling/${pin}/host`;
    const topicClient = `acve/signaling/${pin}/client`;

    const mqttOptions: mqtt.IClientOptions = {};
    if (import.meta.env.VITE_MQTT_USERNAME)
      mqttOptions.username = import.meta.env.VITE_MQTT_USERNAME;
    if (import.meta.env.VITE_MQTT_PASSWORD)
      mqttOptions.password = import.meta.env.VITE_MQTT_PASSWORD;

    const client = mqtt.connect(brokerUrl, mqttOptions);

    client.on("connect", async () => {
      console.log("Connected to MQTT broker, starting WebRTC negotiation...");
      client.subscribe(topicHost);

      const pc = new RTCPeerConnection({
        iceServers: [{ urls: "stun:stun.l.google.com:19302" }],
      });
      pcRef.current = pc;

      const dc = pc.createDataChannel("telemetry", {
        ordered: false,
        maxRetransmits: 0,
      });

      dc.onopen = () => {
        console.log("WebRTC P2P channel opened!");
        setStatus("connected");
        setIsConnected(true);
        client.end();
      };

      dc.onclose = () => {
        console.log("WebRTC channel closed.");
        setStatus("disconnected");
        setIsConnected(false);
        setTelemetry(null);
      };

      dc.onmessage = (e) => {
        try {
          const data: TelemetryData = JSON.parse(e.data);
          setTelemetry(data);
        } catch (error) {
          console.error("Error parsing WebRTC data:", error);
        }
      };

      pc.onicecandidate = (e) => {
        if (e.candidate) {
          client.publish(
            topicClient,
            JSON.stringify({
              type: "candidate",
              candidate: e.candidate.toJSON(),
            }),
          );
        }
      };

      const offer = await pc.createOffer();
      await pc.setLocalDescription(offer);

      client.publish(
        topicClient,
        JSON.stringify({
          type: offer.type,
          sdp: offer.sdp,
        }),
      );
    });

    client.on("message", async (_, message) => {
      try {
        const data = JSON.parse(message.toString());
        if (data.type === "answer" && pcRef.current) {
          await pcRef.current.setRemoteDescription(
            new RTCSessionDescription(data),
          );
        }
      } catch (err) {
        console.error("Error receiving signaling answer:", err);
      }
    });

    client.on("error", (err) => {
      console.error("MQTT connection error:", err);
      setStatus("disconnected");
    });
  };

  useEffect(() => {
    return () => {
      if (pcRef.current) {
        pcRef.current.close();
      }
    };
  }, []);

  const formatGear = (gear: number) => {
    if (gear === -1) return "R";
    if (gear === 0) return "N";
    return gear.toString();
  };

  const formatPedal = (value: number) => {
    return `${Math.round(value * 100)}%`;
  };

  const formatTime = (ms: number) => {
    if (!ms || ms === 0) return "--:--.---";
    const minutes = Math.floor(ms / 60000);
    const seconds = Math.floor((ms % 60000) / 1000);
    const milliseconds = ms % 1000;
    return `${minutes}:${seconds.toString().padStart(2, "0")}.${milliseconds.toString().padStart(3, "0")}`;
  };

  let mainContent;

  if (!isConnected) {
    mainContent = (
      <div className="flex flex-col items-center justify-center h-[60vh] text-slate-500 space-y-6">
        <AlertTriangle className="w-16 h-16 opacity-50" />
        <div className="text-center space-y-2">
          <p className="text-xl">Waiting for connection to Assetto Corsa...</p>
          <p className="text-sm opacity-70">
            Enter the PIN generated by the backend
          </p>
        </div>

        {/* PIN */}
        <div className="flex flex-col sm:flex-row items-center gap-4 mt-4">
          <input
            type="text"
            maxLength={6}
            value={pin}
            onChange={(e) => setPin(e.target.value.replace(/\D/g, ""))} // Only numbers
            placeholder="123456"
            className="bg-slate-900 border border-slate-700 text-center text-2xl tracking-widest font-mono text-slate-100 rounded-lg px-6 py-3 w-48 focus:outline-none focus:border-blue-500 transition-colors"
          />
          <button
            onClick={startConnection}
            disabled={status === "connecting" || pin.length !== 6}
            className="bg-blue-600 hover:bg-blue-500 disabled:bg-slate-800 disabled:text-slate-600 text-white font-semibold px-8 py-3 rounded-lg transition-colors w-full sm:w-auto"
          >
            {status === "connecting" ? "Connecting..." : "Connect"}
          </button>
        </div>
      </div>
    );
  } else if (!telemetry) {
    mainContent = (
      <div className="flex items-center justify-center h-[60vh] text-slate-500">
        <p className="text-xl animate-pulse">Receiving P2P data...</p>
      </div>
    );
  } else {
    const rpmPercentage = Math.min(
      (telemetry.engine_rpm / telemetry.max_rpm) * 100,
      100,
    );

    mainContent = (
      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-6">
        {/* Session Info - Full Width */}
        <div className="col-span-full bg-slate-900 border border-slate-800 rounded-xl p-4 flex justify-between items-center">
          <div className="flex items-center gap-3">
            <Car className="text-slate-400" />
            <div>
              <p className="text-xs text-slate-500 uppercase tracking-wider">
                Car
              </p>
              <p className="font-semibold">{telemetry.car_name || "Unknown"}</p>
            </div>
          </div>
          <div className="text-right">
            <p className="text-xs text-slate-500 uppercase tracking-wider">
              Track
            </p>
            <p className="font-semibold capitalize">
              {telemetry.track_name || "Unknown"}
            </p>
          </div>
        </div>

        {/* Powertrain: Speed, Gear, RPM */}
        <div className="xl:col-span-2 grid grid-cols-2 gap-6 bg-slate-900 border border-slate-800 rounded-xl p-6">
          <div className="flex flex-col items-center justify-center border-r border-slate-800">
            <Gauge className="text-blue-500 w-8 h-8 mb-4 opacity-50" />
            <div className="text-5xl font-black tabular-nums tracking-tighter">
              {Math.round(telemetry.speed_kmh)}
            </div>
            <div className="text-slate-500 uppercase tracking-widest text-xs mt-2">
              km/h
            </div>
          </div>
          <div className="flex flex-col items-center justify-center">
            <div className="text-6xl font-black text-amber-400">
              {formatGear(telemetry.gear)}
            </div>
            <div className="text-slate-500 uppercase tracking-widest text-xs mt-2 font-mono">
              RPM: {Math.round(telemetry.engine_rpm)}
            </div>
            <div className="w-full bg-slate-800 h-2 mt-4 rounded-full overflow-hidden max-w-30">
              <div
                className={`h-full transition-all duration-75 ${rpmPercentage > 95 ? "bg-red-500" : "bg-amber-400"}`}
                style={{ width: `${rpmPercentage}%` }}
              ></div>
            </div>
          </div>
        </div>

        {/* Timing Deltas */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 flex flex-col justify-center">
          <div className="flex items-center gap-2 mb-4 text-slate-400 border-b border-slate-800 pb-2">
            <Clock className="w-4 h-4" />
            <h2 className="text-sm uppercase tracking-widest font-semibold">
              Timing
            </h2>
          </div>
          <div className="space-y-3 font-mono text-sm">
            <div className="flex justify-between items-center">
              <span className="text-slate-500">Current</span>
              <span className="text-white text-lg">
                {formatTime(telemetry.lap_time)}
              </span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-slate-500">Last</span>
              <span className="text-slate-300">
                {formatTime(telemetry.last_lap)}
              </span>
            </div>
            <div className="flex justify-between items-center text-purple-400">
              <span>Best</span>
              <span>{formatTime(telemetry.best_lap)}</span>
            </div>
          </div>
        </div>

        {/* Pedals Input */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 flex flex-col justify-center space-y-6">
          <div>
            <div className="flex justify-between text-xs mb-2 uppercase tracking-widest text-emerald-500">
              <span>Throttle</span>
              <span>{formatPedal(telemetry.gas)}</span>
            </div>
            <div className="w-full bg-slate-800 h-3 rounded-sm overflow-hidden">
              <div
                className="bg-emerald-500 h-full transition-all duration-75"
                style={{ width: formatPedal(telemetry.gas) }}
              ></div>
            </div>
          </div>
          <div>
            <div className="flex justify-between text-xs mb-2 uppercase tracking-widest text-red-500">
              <span>Brake</span>
              <span>{formatPedal(telemetry.brake)}</span>
            </div>
            <div className="w-full bg-slate-800 h-3 rounded-sm overflow-hidden">
              <div
                className="bg-red-500 h-full transition-all duration-75"
                style={{ width: formatPedal(telemetry.brake) }}
              ></div>
            </div>
          </div>
        </div>

        {/* Advanced Chassis Data (Grid format for 4 corners) */}
        <div className="col-span-full xl:col-span-2 grid grid-cols-2 gap-4 bg-slate-900 border border-slate-800 rounded-xl p-6">
          <div className="col-span-full flex items-center gap-2 mb-2 text-slate-400 border-b border-slate-800 pb-2">
            <ArrowDownToLine className="w-4 h-4" />
            <h2 className="text-sm uppercase tracking-widest font-semibold">
              Suspension Travel (M)
            </h2>
          </div>
          {/* FL & FR */}
          <div className="flex justify-between p-3 bg-slate-950 rounded-lg border border-slate-800">
            <span className="text-slate-500 text-xs">FL</span>
            <span className="font-mono text-sm">
              {telemetry.suspension_height[0].toFixed(3)}
            </span>
          </div>
          <div className="flex justify-between p-3 bg-slate-950 rounded-lg border border-slate-800">
            <span className="text-slate-500 text-xs">FR</span>
            <span className="font-mono text-sm">
              {telemetry.suspension_height[1].toFixed(3)}
            </span>
          </div>
          {/* RL & RR */}
          <div className="flex justify-between p-3 bg-slate-950 rounded-lg border border-slate-800">
            <span className="text-slate-500 text-xs">RL</span>
            <span className="font-mono text-sm">
              {telemetry.suspension_height[2].toFixed(3)}
            </span>
          </div>
          <div className="flex justify-between p-3 bg-slate-950 rounded-lg border border-slate-800">
            <span className="text-slate-500 text-xs">RR</span>
            <span className="font-mono text-sm">
              {telemetry.suspension_height[3].toFixed(3)}
            </span>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 font-sans p-6">
      <header className="flex justify-between items-center mb-8 border-b border-slate-800 pb-4">
        <div className="flex items-center gap-3">
          <Activity className="text-blue-500 w-8 h-8" />
          <h1 className="text-2xl font-bold tracking-wider">
            VIRTUAL RACE ENGINEER
          </h1>
        </div>

        <div className="flex items-center gap-2">
          <div
            className={`w-3 h-3 rounded-full ${isConnected ? "bg-emerald-500 animate-pulse" : "bg-red-500"}`}
          ></div>
          <span className="text-sm font-medium text-slate-400 uppercase tracking-widest">
            {isConnected ? "Telemetry Active" : "Offline"}
          </span>
        </div>
      </header>

      {mainContent}
    </div>
  );
}
