name: Workflows CI

on:
  push:
    paths:
      - ".github/workflows/**.yml"
      - ".github/workflows/**.yaml"
  pull_request:
    paths:
      - ".github/workflows/**.yml"
      - ".github/workflows/**.yaml"

jobs:
  lint-and-format:
    name: Validate and Lint Actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Check YAML Formatting
        run: |
          npx --ignore-scripts prettier --write .github/workflows/
          git diff --exit-code

      - name: Validate Actions Syntax
        uses: raven-actions/actionlint@3d39aea434753780c3b3d4a1a31c854b4dbf49d7
        with:
          flags: -ignore 'missing input "app-id"' -ignore 'input "client-id" is not defined'

      - name: Set up Python for yamllint
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install yamllint
        run: |
          pip install --only-binary :all: yamllint

      - name: Run yamllint
        run: yamllint .github/workflows/
